apiVersion: v1
kind: Pod
metadata:
  name: k3s-gpu-test-known-good
spec:
  restartPolicy: Never
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:12.8.1-base-ubuntu24.04
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: nvidia-libraries
          mountPath: /usr/local/nvidia
          readOnly: true
        - name: nvidia-smi
          mountPath: /usr/bin/nvidia-smi
          readOnly: true
        - name: nix-store
          mountPath: /nix/store
          readOnly: true
  volumes:
    - name: nvidia-libraries
      hostPath:
        path: /usr/local/nvidia
    - name: nvidia-smi
      hostPath:
        path: /usr/bin/nvidia-smi
        type: File
    - name: nix-store
      hostPath:
        path: /nix/store
