apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      serviceAccountName: nvidia-device-plugin
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      containers:
        - image: nvcr.io/nvidia/k8s-device-plugin:v0.17.1
          name: nvidia-device-plugin-ctr
          args:
            - --fail-on-init-error=false
            - --device-list-strategy=cdi-cri
            - --pass-device-specs=false
            - --container-driver-root=/driver-root
            - --nvidia-driver-root=/run/k3s-nvidia/driver
            - --nvidia-dev-root=/
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: nvidia-driver-root
              mountPath: /driver-root
              readOnly: true
            - name: nvidia-libraries
              mountPath: /usr/local/nvidia/lib64
              readOnly: true
            - name: host-dev
              mountPath: /dev
            - name: cdi
              mountPath: /var/run/cdi
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: nvidia-driver-root
          hostPath:
            path: /run/k3s-nvidia/driver
        - name: nvidia-libraries
          hostPath:
            path: /run/k3s-nvidia/driver/lib64
        - name: host-dev
          hostPath:
            path: /dev
        - name: cdi
          hostPath:
            path: /var/run/cdi
